/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCarouselCustom: typeof import('./src/components/AppCarouselCustom.vue')['default']
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    AppMainFooter: typeof import('./src/components/layout/AppMainFooter.vue')['default']
    AppMainMenu: typeof import('./src/components/layout/AppMainMenu.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppModalContact: typeof import('./src/components/AppModalContact.vue')['default']
    AppModalImage: typeof import('./src/components/AppModalImage.vue')['default']
    AppPolaroidsSingle: typeof import('./src/components/AppPolaroidsSingle.vue')['default']
    AppSocialLinks: typeof import('./src/components/layout/AppSocialLinks.vue')['default']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
